using KnowledgeHub.Server.Domain.Entities;
using KnowledgeHub.Server.Ingestion.Connectors;
using KnowledgeHub.Shared.Contracts;
using Microsoft.Extensions.Logging.Abstractions;

namespace KnowledgeHub.Tests.Unit.Ingestion;

// Covers SPEC-20260927-youtube-transcript-connector RF-004/RF-005/RF-007:
// discovery (video/playlist/channel), maxVideos/Truncated, track selection,
// fingerprint/stub skip, forceRefresh, FetchItemAsync, warnings/FailedUris.
public class YouTubeConnectorTests
{
    private sealed class FakeYouTubeClient : IYouTubeClient
    {
        private readonly Dictionary<string, VideoInfo> _videos = new();
        private readonly Dictionary<string, List<VideoInfo>> _playlists = new();
        private readonly Dictionary<string, List<VideoInfo>> _channels = new();
        private readonly Dictionary<string, List<CaptionTrackInfo>> _manifests = new();
        private readonly Dictionary<(string VideoId, string Lang, bool Auto), List<Caption>> _tracks = new();

        public int ManifestCalls { get; private set; }
        public int TrackCalls { get; private set; }

        public FakeYouTubeClient AddVideo(string id, string title = "Test", int durationSecs = 60)
        {
            _videos[id] = new VideoInfo(id, title, "TestChannel", TimeSpan.FromSeconds(durationSecs));
            return this;
        }

        public FakeYouTubeClient AddPlaylist(string playlistId, params string[] videoIds)
        {
            _playlists[playlistId] = videoIds
                .Select(id => _videos.GetValueOrDefault(id)
                    ?? new VideoInfo(id, $"Video {id}", "TestChannel", TimeSpan.FromSeconds(60)))
                .ToList();
            return this;
        }

        public FakeYouTubeClient AddChannel(string channelId, params string[] videoIds)
        {
            _channels[channelId] = videoIds
                .Select(id => _videos.GetValueOrDefault(id)
                    ?? new VideoInfo(id, $"Video {id}", "TestChannel", TimeSpan.FromSeconds(60)))
                .ToList();
            return this;
        }

        public FakeYouTubeClient AddCaptions(string videoId, string language, bool isAuto, params string[] texts)
        {
            if (!_manifests.ContainsKey(videoId))
                _manifests[videoId] = [];
            _manifests[videoId].Add(new CaptionTrackInfo(language, isAuto));
            _tracks[(videoId, language, isAuto)] = texts
                .Select((t, i) => new Caption(t, TimeSpan.FromSeconds(i * 2)))
                .ToList();
            return this;
        }

        private string? _currentVideoId;

        public Task<VideoInfo> GetVideoAsync(string videoId, CancellationToken ct)
        {
            _currentVideoId = videoId;
            if (!_videos.TryGetValue(videoId, out var v))
                throw new Exception("Video not found");
            return Task.FromResult(v);
        }

        public async IAsyncEnumerable<VideoInfo> GetPlaylistVideosAsync(
            string playlistId, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct)
        {
            if (_playlists.TryGetValue(playlistId, out var videos))
                foreach (var v in videos)
                    yield return v;
            await Task.CompletedTask;
        }

        public async IAsyncEnumerable<VideoInfo> GetChannelUploadsAsync(
            string channelIdOrHandle, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct)
        {
            if (_channels.TryGetValue(channelIdOrHandle, out var videos))
                foreach (var v in videos)
                    yield return v;
            await Task.CompletedTask;
        }

        public Task<IReadOnlyList<CaptionTrackInfo>> GetCaptionManifestAsync(string videoId, CancellationToken ct)
        {
            _currentVideoId = videoId;
            ManifestCalls++;
            if (!_manifests.TryGetValue(videoId, out var tracks))
                return Task.FromResult<IReadOnlyList<CaptionTrackInfo>>([]);
            return Task.FromResult<IReadOnlyList<CaptionTrackInfo>>(tracks);
        }

        public Task<IReadOnlyList<Caption>> GetCaptionTrackAsync(CaptionTrackInfo track, CancellationToken ct)
        {
            TrackCalls++;
            if (_currentVideoId is not null
                && _tracks.TryGetValue((_currentVideoId, track.Language, track.IsAutoGenerated), out var captions))
                return Task.FromResult<IReadOnlyList<Caption>>(captions);
            return Task.FromResult<IReadOnlyList<Caption>>([]);
        }
    }

    private static KnowledgeSource Source(object configuration) => new()
    {
        Id = Guid.NewGuid(),
        Name = "yt-src",
        SourceType = SourceType.YouTube,
        ConfigurationJson = System.Text.Json.JsonSerializer.Serialize(configuration)
    };

    private static YouTubeConnector Sut(FakeYouTubeClient client) =>
        new(client, NullLogger<YouTubeConnector>.Instance);

    [Fact]
    public async Task SingleVideo_TranscribesAndIndexes()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("dQw4w9WgXcQ", "My Talk")
            .AddCaptions("dQw4w9WgXcQ", "en", false, "Hello world", "Goodbye world");

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "https://youtu.be/dQw4w9WgXcQ" } }), CancellationToken.None);

        var doc = Assert.Single(result.Documents);
        Assert.Equal("yt://video/dQw4w9WgXcQ", doc.UriReference);
        Assert.Equal("My Talk", doc.Title);
        Assert.Contains("Hello world", doc.TextContent);
        Assert.Contains("Goodbye world", doc.TextContent);
        Assert.Equal("yt:dQw4w9WgXcQ", doc.Fingerprint);
        Assert.Equal(1, client.ManifestCalls);
        Assert.Equal(1, client.TrackCalls);
    }

    [Fact]
    public async Task Incremental_FingerprintMatch_SkipsManifestCall()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("dQw4w9WgXcQ", "My Talk")
            .AddCaptions("dQw4w9WgXcQ", "en", false, "Hello");

        var fingerprints = new Dictionary<string, string>
        {
            ["yt://video/dQw4w9WgXcQ"] = "yt:dQw4w9WgXcQ"
        };

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "https://youtu.be/dQw4w9WgXcQ" } }),
            fingerprints, CancellationToken.None);

        var doc = Assert.Single(result.Documents);
        Assert.Equal("", doc.TextContent); // stub
        Assert.Equal(0, client.ManifestCalls);
        Assert.Equal(0, client.TrackCalls);
    }

    [Fact]
    public async Task ForceRefresh_BypassesFingerprintMatch()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("dQw4w9WgXcQ", "My Talk")
            .AddCaptions("dQw4w9WgXcQ", "en", false, "Hello");

        var fingerprints = new Dictionary<string, string>
        {
            ["yt://video/dQw4w9WgXcQ"] = "yt:dQw4w9WgXcQ"
        };

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "https://youtu.be/dQw4w9WgXcQ" }, forceRefresh = true }),
            fingerprints, CancellationToken.None);

        var doc = Assert.Single(result.Documents);
        Assert.NotEqual("", doc.TextContent);
        Assert.Equal(1, client.ManifestCalls);
        Assert.Equal(1, client.TrackCalls);
    }

    [Fact]
    public async Task Playlist_ExpandsToVideos()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("vid00000001", "First")
            .AddVideo("vid00000002", "Second")
            .AddCaptions("vid00000001", "en", false, "alpha body")
            .AddCaptions("vid00000002", "en", false, "beta body")
            .AddPlaylist("PL123", "vid00000001", "vid00000002");

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "https://youtube.com/playlist?list=PL123" } }),
            CancellationToken.None);

        Assert.Equal(2, result.Documents.Count);
        Assert.Contains("alpha body", result.Documents[0].TextContent);
        Assert.Contains("beta body", result.Documents[1].TextContent);
    }

    [Fact]
    public async Task MaxVideos_TruncatesWithFlag()
    {
        var client = new FakeYouTubeClient();
        var ids = new[] { "vid00000001", "vid00000002", "vid00000003", "vid00000004", "vid00000005" };
        for (var i = 0; i < 5; i++)
        {
            client.AddVideo(ids[i], $"Video {i}");
            client.AddCaptions(ids[i], "en", false, $"content {i}");
        }
        client.AddPlaylist("PL1234567890", ids);

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "PL1234567890" }, maxVideos = 3 }), CancellationToken.None);

        Assert.Equal(3, result.Documents.Count);
        Assert.True(result.Truncated);
        Assert.Contains(result.Warnings, w => w.Contains("maxVideos"));
    }

    [Fact]
    public async Task VideoWithoutCaptions_SkippedWithWarning()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("vid00000001", "Has Captions")
            .AddVideo("vid00000002", "No Captions")
            .AddCaptions("vid00000001", "en", false, "content");

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "vid00000001", "vid00000002" } }), CancellationToken.None);

        Assert.Single(result.Documents);
        Assert.Contains(result.Warnings, w => w.Contains("No Captions") || w.Contains("legendas"));
    }

    [Fact]
    public async Task SameVideoInMultipleUrls_Deduplicated()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("dQw4w9WgXcQ", "My Talk")
            .AddCaptions("dQw4w9WgXcQ", "en", false, "Hello");

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "https://youtu.be/dQw4w9WgXcQ", "https://youtube.com/watch?v=dQw4w9WgXcQ" } }),
            CancellationToken.None);

        Assert.Single(result.Documents);
    }

    [Fact]
    public async Task LanguagePreference_ManualMatchingLanguage_BeatsAutoMatchingLanguage()
    {
        // SPEC RF-005 priority: (1) manual + language match beats (3) auto + language match.
        var client = new FakeYouTubeClient()
            .AddVideo("vid00000001", "Polyglot")
            .AddCaptions("vid00000001", "en", false, "English text")
            .AddCaptions("vid00000001", "pt-BR", true, "Texto em portugues");

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "vid00000001" }, language = "pt" }), CancellationToken.None);

        // (2) "any manual" beats (3) "auto + language match" — English manual wins.
        var doc = Assert.Single(result.Documents);
        Assert.Contains("English text", doc.TextContent);
    }

    [Fact]
    public async Task LanguagePreference_ManualMatchingLanguage_BeatsAnyManual()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("vid00000001", "Polyglot")
            .AddCaptions("vid00000001", "en", false, "English text")
            .AddCaptions("vid00000001", "pt", false, "Texto em portugues");

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "vid00000001" }, language = "pt" }), CancellationToken.None);

        var doc = Assert.Single(result.Documents);
        Assert.Contains("portugues", doc.TextContent);
    }

    [Fact]
    public async Task InvalidUrl_GeneratesWarning()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("vid00000001", "Valid")
            .AddCaptions("vid00000001", "en", false, "content");

        var result = await Sut(client).FetchAsync(
            Source(new { urls = new[] { "notaurl", "vid00000001" } }), CancellationToken.None);

        Assert.Single(result.Documents);
        Assert.Contains(result.Warnings, w => w.Contains("notaurl") || w.Contains("não reconhecida"));
    }

    [Fact]
    public async Task FetchItemAsync_ReturnsMatchingVideo()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("dQw4w9WgXcQ", "My Talk")
            .AddCaptions("dQw4w9WgXcQ", "en", false, "Hello world");

        var doc = await Sut(client).FetchItemAsync(
            Source(new { urls = new[] { "dQw4w9WgXcQ" } }),
            "yt://video/dQw4w9WgXcQ", CancellationToken.None);

        Assert.NotNull(doc);
        Assert.Equal("My Talk", doc!.Title);
        Assert.Contains("Hello world", doc.TextContent);
    }

    [Fact]
    public async Task FetchItemAsync_ItemNotFound_ReturnsNull()
    {
        var client = new FakeYouTubeClient()
            .AddVideo("vid00000001", "Exists")
            .AddCaptions("vid00000001", "en", false, "content");

        var doc = await Sut(client).FetchItemAsync(
            Source(new { urls = new[] { "vid00000001" } }),
            "yt://video/nonexistent", CancellationToken.None);

        Assert.Null(doc);
    }
}
