// <auto-generated />
﻿using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace KnowledgeHub.Server.Migrations.Postgres
{
    /// <inheritdoc />
    public partial class TemporalEpisodicGraph : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<Guid>(
                name: "EpisodeId",
                table: "KgNodes",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<List<string>>(
                name: "Labels",
                table: "KgNodes",
                type: "text[]",
                nullable: false);

            migrationBuilder.AddColumn<DateTime>(
                name: "ObservedAt",
                table: "KgNodes",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<DateTime>(
                name: "ValidFrom",
                table: "KgNodes",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<DateTime>(
                name: "ValidTo",
                table: "KgNodes",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "EpisodeId",
                table: "KgEdges",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ObservedAt",
                table: "KgEdges",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<string>(
                name: "PropertiesJson",
                table: "KgEdges",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "ValidFrom",
                table: "KgEdges",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<DateTime>(
                name: "ValidTo",
                table: "KgEdges",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<double>(
                name: "Weight",
                table: "KgEdges",
                type: "double precision",
                nullable: false,
                defaultValue: 0.0);

            migrationBuilder.CreateTable(
                name: "KgEpisodes",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Kind = table.Column<string>(type: "character varying(24)", maxLength: 24, nullable: false),
                    KnowledgeSourceId = table.Column<Guid>(type: "uuid", nullable: true),
                    ThreadId = table.Column<Guid>(type: "uuid", nullable: true),
                    Summary = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    CreatedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    EndedAt = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_KgEpisodes", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_KgNodes_EpisodeId",
                table: "KgNodes",
                column: "EpisodeId");

            migrationBuilder.CreateIndex(
                name: "IX_KgNodes_ObservedAt",
                table: "KgNodes",
                column: "ObservedAt");

            migrationBuilder.CreateIndex(
                name: "IX_KgEdges_EpisodeId",
                table: "KgEdges",
                column: "EpisodeId");

            migrationBuilder.CreateIndex(
                name: "IX_KgEdges_ObservedAt",
                table: "KgEdges",
                column: "ObservedAt");

            migrationBuilder.CreateIndex(
                name: "IX_KgEpisodes_CreatedAt",
                table: "KgEpisodes",
                column: "CreatedAt");

            migrationBuilder.CreateIndex(
                name: "IX_KgEpisodes_KnowledgeSourceId",
                table: "KgEpisodes",
                column: "KnowledgeSourceId");

            migrationBuilder.CreateIndex(
                name: "IX_KgEpisodes_ThreadId",
                table: "KgEpisodes",
                column: "ThreadId");

            migrationBuilder.AddForeignKey(
                name: "FK_KgEdges_KgEpisodes_EpisodeId",
                table: "KgEdges",
                column: "EpisodeId",
                principalTable: "KgEpisodes",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);

            migrationBuilder.AddForeignKey(
                name: "FK_KgNodes_KgEpisodes_EpisodeId",
                table: "KgNodes",
                column: "EpisodeId",
                principalTable: "KgEpisodes",
                principalColumn: "Id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_KgEdges_KgEpisodes_EpisodeId",
                table: "KgEdges");

            migrationBuilder.DropForeignKey(
                name: "FK_KgNodes_KgEpisodes_EpisodeId",
                table: "KgNodes");

            migrationBuilder.DropTable(
                name: "KgEpisodes");

            migrationBuilder.DropIndex(
                name: "IX_KgNodes_EpisodeId",
                table: "KgNodes");

            migrationBuilder.DropIndex(
                name: "IX_KgNodes_ObservedAt",
                table: "KgNodes");

            migrationBuilder.DropIndex(
                name: "IX_KgEdges_EpisodeId",
                table: "KgEdges");

            migrationBuilder.DropIndex(
                name: "IX_KgEdges_ObservedAt",
                table: "KgEdges");

            migrationBuilder.DropColumn(
                name: "EpisodeId",
                table: "KgNodes");

            migrationBuilder.DropColumn(
                name: "Labels",
                table: "KgNodes");

            migrationBuilder.DropColumn(
                name: "ObservedAt",
                table: "KgNodes");

            migrationBuilder.DropColumn(
                name: "ValidFrom",
                table: "KgNodes");

            migrationBuilder.DropColumn(
                name: "ValidTo",
                table: "KgNodes");

            migrationBuilder.DropColumn(
                name: "EpisodeId",
                table: "KgEdges");

            migrationBuilder.DropColumn(
                name: "ObservedAt",
                table: "KgEdges");

            migrationBuilder.DropColumn(
                name: "PropertiesJson",
                table: "KgEdges");

            migrationBuilder.DropColumn(
                name: "ValidFrom",
                table: "KgEdges");

            migrationBuilder.DropColumn(
                name: "ValidTo",
                table: "KgEdges");

            migrationBuilder.DropColumn(
                name: "Weight",
                table: "KgEdges");
        }
    }
}
