namespace KnowledgeHub.Server.Ingestion.Connectors;

/// <summary>
/// Testable seam over YoutubeExplode (SPEC-20260927-youtube-transcript-connector
/// RF-003): exposes only the operations the connector needs — video metadata,
/// playlist expansion, channel uploads, and closed caption manifest/track.
/// </summary>
public interface IYouTubeClient
{
    Task<VideoInfo> GetVideoAsync(string videoId, CancellationToken ct);
    IAsyncEnumerable<VideoInfo> GetPlaylistVideosAsync(string playlistId, CancellationToken ct);
    IAsyncEnumerable<VideoInfo> GetChannelUploadsAsync(string channelIdOrHandle, CancellationToken ct);
    Task<IReadOnlyList<CaptionTrackInfo>> GetCaptionManifestAsync(string videoId, CancellationToken ct);
    Task<IReadOnlyList<Caption>> GetCaptionTrackAsync(CaptionTrackInfo track, CancellationToken ct);
}

/// <summary>Normalized video metadata.</summary>
public sealed record VideoInfo(string Id, string Title, string Author, TimeSpan Duration);

/// <summary>One available caption track.</summary>
public sealed record CaptionTrackInfo(string Language, bool IsAutoGenerated);

/// <summary>One caption line with offset.</summary>
public sealed record Caption(string Text, TimeSpan Offset);
