using YoutubeExplode;
using YoutubeExplode.Common;
using YoutubeExplode.Playlists;
using YoutubeExplode.Videos;
using YoutubeExplode.Videos.ClosedCaptions;

namespace KnowledgeHub.Server.Ingestion.Connectors;

/// <summary>
/// Production adapter over <see cref="YoutubeClient"/> (SPEC-20260927-
/// youtube-transcript-connector RF-003). Delegates to YoutubeExplode's
/// Videos, Playlists, Channels and ClosedCaptions APIs. Exceptions from
/// YoutubeExplode propagate to the connector for per-item handling.
/// </summary>
public sealed class YouTubeClientAdapter : IYouTubeClient
{
    private readonly YoutubeClient _client = new();

    public async Task<VideoInfo> GetVideoAsync(string videoId, CancellationToken ct)
    {
        var video = await _client.Videos.GetAsync(videoId);
        return new VideoInfo(
            video.Id.Value,
            video.Title,
            video.Author.ChannelTitle ?? "Unknown",
            video.Duration ?? TimeSpan.Zero);
    }

    public async IAsyncEnumerable<VideoInfo> GetPlaylistVideosAsync(
        string playlistId, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct)
    {
        await foreach (var video in _client.Playlists.GetVideosAsync(playlistId).WithCancellation(ct))
            yield return new VideoInfo(
                video.Id.Value,
                video.Title,
                video.Author.ChannelTitle ?? "Unknown",
                video.Duration ?? TimeSpan.Zero);
    }

    public async IAsyncEnumerable<VideoInfo> GetChannelUploadsAsync(
        string channelIdOrHandle, [System.Runtime.CompilerServices.EnumeratorCancellation] CancellationToken ct)
    {
        await foreach (var video in _client.Channels.GetUploadsAsync(channelIdOrHandle).WithCancellation(ct))
            yield return new VideoInfo(
                video.Id.Value,
                video.Title,
                video.Author.ChannelTitle ?? "Unknown",
                video.Duration ?? TimeSpan.Zero);
    }

    public async Task<IReadOnlyList<CaptionTrackInfo>> GetCaptionManifestAsync(
        string videoId, CancellationToken ct)
    {
        var manifest = await _client.Videos.ClosedCaptions.GetManifestAsync(videoId);
        return manifest.Tracks
            .Select(t => new CaptionTrackInfo(t.Language.Code, t.IsAutoGenerated))
            .ToList();
    }

    public async Task<IReadOnlyList<Caption>> GetCaptionTrackAsync(
        CaptionTrackInfo track, CancellationToken ct)
    {
        var manifest = await _client.Videos.ClosedCaptions.GetManifestAsync(
            track.Language); // Re-fetch by language — YoutubeExplode's track object
                             // is not serializable across calls; we match by language+auto.
        var matchedTrack = manifest.Tracks
            .FirstOrDefault(t => t.Language.Code == track.Language
                && t.IsAutoGenerated == track.IsAutoGenerated)
            ?? manifest.Tracks
                .FirstOrDefault(t => t.Language.Code == track.Language);

        if (matchedTrack is null)
            return [];

        var captions = await _client.Videos.ClosedCaptions.GetAsync(matchedTrack);
        return captions.Captions
            .Select(c => new Caption(c.Text, c.Offset))
            .ToList();
    }
}
