using System.Text;
using KnowledgeHub.Review.Gate;
using KnowledgeHub.Review.Review;
using KnowledgeHub.Review.Signals;

namespace KnowledgeHub.Review.Output;

/// <summary>
/// RF-005 — renders the idempotent summary comment (marker
/// <c>&lt;!-- knowledge-review --&gt;</c>) with Overview / Stack / Bugs /
/// Style / Security / Flags / Verdict sections in the configured language.
/// </summary>
public static class SummaryCommentRenderer
{
    public const string Marker = "<!-- knowledge-review -->";

    public static string Render(PullRequestSignal signal, AnalysisResult analysis, VerdictResult verdict,
        string language, bool hubReachable)
    {
        var pt = language.StartsWith("pt", StringComparison.OrdinalIgnoreCase);
        string T(string en, string ptBr) => pt ? ptBr : en;

        var sb = new StringBuilder();
        sb.AppendLine(Marker);
        sb.AppendLine(pt ? "## Knowledge Review" : "## Knowledge Review");
        sb.AppendLine();

        sb.AppendLine(T("### Overview", "### Visão geral"));
        sb.AppendLine(string.IsNullOrWhiteSpace(analysis.Summary)
            ? T($"_{signal.Files.Count} file(s) analyzed._", $"_{signal.Files.Count} arquivo(s) analisados._")
            : analysis.Summary);
        sb.AppendLine();

        if (signal.IsStacked)
        {
            sb.AppendLine(T("### Stack (diff = this layer only)", "### Stack (diff = só esta camada)"));
            foreach (var l in signal.StackChain)
                sb.AppendLine($"- #{l.Number} `{l.HeadRef}` → `{l.BaseRef}`{(l.ChecksFailing ? T(" — checks failing", " — checks falhando") : "")}");
            sb.AppendLine($"- **#{signal.Number}** `{signal.Meta.HeadRef}` {T("(this)", "(este)")}");
            sb.AppendLine();
        }

        Section(sb, T("### Bugs", "### Bugs"), analysis.Findings.Where(f => f.Kind == "bug"));
        Section(sb, T("### Style", "### Estilo"), analysis.Findings.Where(f => f.Kind == "style"));
        Section(sb, T("### Security", "### Segurança"), analysis.Findings.Where(f => f.Kind == "security"));
        Section(sb, T("### Flags", "### Flags"), analysis.Findings.Where(f => f.Kind == "flag"));

        sb.AppendLine(T("### Verdict", "### Veredito"));
        var icon = verdict.Verdict switch
        {
            Verdict.Approved => "✅",
            Verdict.Skipped => "⏭️",
            Verdict.Inconclusive => "⏳",
            _ => "⚠️",
        };
        sb.AppendLine($"{icon} **{verdict.Verdict.ToString().ToUpperInvariant()}** — {verdict.StatusDescription}");
        foreach (var r in verdict.Reasons)
            sb.AppendLine($"- {r}");
        if (!hubReachable)
            sb.AppendLine(T("_hub unreachable — review ran in local mode_", "_hub inacessível — review executado em modo local_"));
        if (analysis.SummaryOnly)
            sb.AppendLine(T("_summary mode — oversized diff_", "_modo resumo — diff acima do limite_"));
        sb.AppendLine();
        sb.AppendLine(T(
            "<sub>Generated by Knowledge Review (self-hosted). Signal schema v" + signal.SchemaVersion + ".</sub>",
            "<sub>Gerado por Knowledge Review (self-hosted). Schema de sinais v" + signal.SchemaVersion + ".</sub>"));
        return sb.ToString();
    }

    private static void Section(StringBuilder sb, string title, IEnumerable<Finding> findings)
    {
        var list = findings.ToList();
        if (list.Count == 0) return;
        sb.AppendLine(title);
        foreach (var f in list)
        {
            var loc = f.File is { } file ? $"`{file}`{(f.Line is { } l ? $":{l}" : "")}" : "_repo-level_";
            var cwe = f.Cwe is { } c ? $" ({c})" : "";
            sb.AppendLine($"- **{f.Severity}** {loc}{cwe} — {f.Rationale}");
        }
        sb.AppendLine();
    }
}
